[Rainmeter]
Update=100
AccurateText=1

; --- FONT DOSYASINI DOĞRUDAN BELLEĞE YÜKLE ---
LocalFont=#@#Fonts\Cause-Bold.ttf

[Variables]
; ==================== KULLANICI AYARLARI ====================
; 1) Görsel Genişliği
ImageW=500

; 2) SAAT FONT BÜYÜKLÜĞÜ
; İstediğiniz değeri verin (Örn: 25, 35, 50, 70).
FontSize=38

; 3) SAATİN EKRANDAKİ YERİ
; Sola/Sağa kaydırmak için BoxX, Yukarı/Aşağı kaydırmak için BoxY değerini değiştirin:
BoxX=251
BoxY=85

; 4) FONT VE RENK AYARLARI
FontName=Cause
TextColor=ba2fa3FF
; ============================================================

[MeasureTime]
Measure=Time
Format=%H:%M:%S

; --- ARKA PLAN GÖRSELİ ---
[MeterBackground]
Meter=Image
ImageName=#@#bocchi-balonlu-bitsi.png
W=#ImageW#
PreserveAspectRatio=1

; --- SAAT METNİ ---
[MeterClock]
Meter=String
MeasureName=MeasureTime
FontFace=#FontName#
FontSize=#FontSize#
FontColor=#TextColor#
StringAlign=Center
StringStyle=Bold
X=#BoxX#
Y=#BoxY#
ClipString=0
DynamicVariables=1